\section{Eccezioni (note 8)}
\subsection*{Esercizio 5.1}
Si dia la semantica operazionale dei termini indicati sopra, osservando come il sollevamento delle eccezioni comporti un salto non locale del flusso di controllo.
Sia M = fn x.(if pari(x) then x/2 else throw x)
\begin{itemize}
	\item try (M 3) catch fn y.y + y
	\item try (fn y.y - 2 (M 5)) catch fn z.print(z)
	\item try (fn y.y - 2 (M throw 2)) catch fn z.print(z)
	\item try (fn y.y - 2 (try (M 5) catch fn z.z+z)) catch fn z.print(z)
	\item try ((fn x.x throw 1) (try (M 5) catch fn z.z+z)) catch fn z.print(z)
\end{itemize}  

\subsubsection*{Svolgimento} 

\paragraph{a) try (M 3) catch fn y.y + y}\mbox{}

\textbf{passo 1} 
\begin{prooftree} 
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{M 3 = fn x.(if pari(x) then x/2 else throw x) 3 $\rightarrow$ if pari(3) then 3/2 else throw 3}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (M 3) catch fn y.y + y $\rightarrow$ try (if pari(3) then 3/2 else throw 3) catch fn y.y + y}
\end{prooftree}
  
\textbf{passo 2} \\		
\scalebox{.9}{
\parbox{1cm}{
\begin{prooftree} 
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{pari(3) $\rightarrow$ false}
	\LeftLabel{\textsc{(IF)}}
	\UnaryInfC{if pari(3) then 3/2 else throw 3 $\rightarrow$ if false then 3/2 else throw 3}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (if pari(3) then 3/2 else throw 3) catch fn y.y + y $\rightarrow$ try (if false then 3/2 else throw 3) catch fn y.y + y}
\end{prooftree}}
} 

\textbf{passo 3} 
\begin{prooftree}  
	\AxiomC{\textsc{(IF-FALSE)}}
	\UnaryInfC{if false then 3/2 else throw 3 $\rightarrow$ throw 3}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (if false then 3/2 else throw 3) catch fn y.y + y $\rightarrow$ try (throw 3) catch fn y.y + y}
\end{prooftree}

\textbf{passo 4} 
\begin{prooftree}   
	\AxiomC{\textsc{(TRY HANDLE)}}
	\UnaryInfC{try (throw 3) catch fn y.y + y $\rightarrow$ fn y.y + y 3}
\end{prooftree}

Al passo 4 si effettua un salto non locale del flusso di controllo a causa dell'eccezione.

\textbf{passo 5} 
\begin{prooftree}   
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{fn y.y + y 3 $\rightarrow$ 3 + 3}
\end{prooftree}

\textbf{passo 6} 
\begin{prooftree}   
	\AxiomC{\textsc{(SUM)}}
	\UnaryInfC{3 + 3 $\rightarrow$ 6}
\end{prooftree}


L'eccezione lanciata dal throw x in M viene raccolta dall'unico catch presente.

\paragraph{b) try (fn y.y - 2 (M 5)) catch fn z.print(z)}\mbox{}

\textbf{passo 1} 
\begin{prooftree} 
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{M 5 = fn x.(if pari(x) then x/2 else throw x) 5 $\rightarrow$ if pari(5) then 5/2 else throw 5}
	\LeftLabel{\textsc{(APP 2)}}
	\UnaryInfC{fn y.y - 2 (M 5) $\rightarrow$ fn y.y - 2 (M\{x=5\})}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (M 5)) catch fn z.print(z) $\rightarrow$ try (fn y.y - 2 (M\{x=5\})) catch fn z.print(z)}
\end{prooftree}

\textbf{passo 2} 
\begin{prooftree} 
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{pari(5) $\rightarrow$ false}
	\LeftLabel{\textsc{(IF)}}
	\UnaryInfC{(M\{x=5\}) = if pari(5) then 5/2 else throw 5 $\rightarrow$ if false then 5/2 else throw 5}
	\LeftLabel{\textsc{(APP 2)}}
	\UnaryInfC{fn y.y - 2 (M\{x=5\}) $\rightarrow$ fn y.y - 2 (M'\{x=5\})}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (M\{x=5\})) catch fn z.print(z) $\rightarrow$ try (fn y.y - 2 (M'\{x=5\})) catch fn z.print(z)}
\end{prooftree}

\textbf{passo 3} 
\begin{prooftree} 
	\AxiomC{\textsc{(IF-FALSE)}}
	\UnaryInfC{(M'\{x=5\}) = if false then 5/2 else throw 5 $\rightarrow$ throw 5}
	\LeftLabel{\textsc{(APP 2)}}
	\UnaryInfC{fn y.y - 2 (M'\{x=5\}) $\rightarrow$ fn y.y - 2 (throw 5)}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (M'\{x=5\})) catch fn z.print(z) $\rightarrow$ try (fn y.y - 2 (throw 5)) catch fn z.print(z)}
\end{prooftree}

\textbf{passo 4} 
\begin{prooftree}  
	\AxiomC{\textsc{(RAISE APP 2)}}
	\UnaryInfC{fn y.y - 2 (throw 5) $\rightarrow$ (throw 5)}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (throw 5)) catch fn z.print(z) $\rightarrow$ try (throw 5) catch fn z.print(z)}
\end{prooftree}

Al passo 4 si effettua un salto non locale del flusso di controllo a causa dell'eccezione.

\textbf{passo 5} 
\begin{prooftree}   
	\AxiomC{\textsc{(TRY HANDLE)}}
	\UnaryInfC{try (throw 5) catch fn z.print(z) $\rightarrow$ fn z.print(z) 5}
\end{prooftree}

\textbf{passo 6} 
\begin{prooftree}   
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{fn z.print(z) 5 $\rightarrow$ print(5)}
\end{prooftree}

\textbf{passo 7} 
\begin{prooftree}   
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{print(5) $\rightarrow$ "stampa 5"}
\end{prooftree}

L'eccezione lanciata dal throw x in M viene raccolta dall'unico catch presente.

\paragraph{c) try (fn y.y - 2 (M throw 2)) catch fn z.print(z)}\mbox{}

\textbf{passo 1} 
\begin{prooftree} 
	\AxiomC{\textsc{(RAISE APP 2)}}
	\UnaryInfC{M throw 2 = fn x.(if pari(x) then x/2 else throw x) throw 2 $\rightarrow$ throw 2}
	\LeftLabel{\textsc{(APP 2)}}
	\UnaryInfC{fn y.y - 2 (M throw 2) $\rightarrow$ fn y.y - 2 (throw 2)}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (M throw 2)) catch fn z.print(z) $\rightarrow$ try (fn y.y - 2 (throw 2)) catch fn z.print(z)}
\end{prooftree}

\textbf{passo 2} 
\begin{prooftree}  
	\AxiomC{\textsc{(RAISE APP 2)}}
	\UnaryInfC{fn y.y - 2 (throw 2) $\rightarrow$ throw 2}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (throw 2)) catch fn z.print(z) $\rightarrow$ try (throw 2) catch fn z.print(z)}
\end{prooftree}

Ai passi 1 e 2 si effettuano dei salti non locali del flusso di controllo a causa dell'eccezione.

\textbf{passo 3} 
\begin{prooftree}   
	\AxiomC{\textsc{(TRY HANDLE)}}
	\UnaryInfC{try (throw 2) catch fn z.print(z) $\rightarrow$ fn z.print(z) 2}
\end{prooftree}

\textbf{passo 4} 
\begin{prooftree}   
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{fn z.print(z) 2 $\rightarrow$ print(2)}
\end{prooftree}

\textbf{passo 5} 
\begin{prooftree}   
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{print(2) $\rightarrow$ "stampa 2"}
\end{prooftree}

L'eccezione lanciata da throw 2 viene raccolta dall'unico catch presente.

\paragraph{d) try (fn y.y - 2 (try (M 5) catch fn z.z+z)) catch fn z.print(z)}\mbox{}

\textbf{passo 1} \\		
\scalebox{.75}{
\parbox{1cm}{ 
\begin{prooftree} 
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{M 5 = fn x.(if pari(x) then x/2 else throw x) 5 $\rightarrow$ if pari(5) then 5/2 else throw 5}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (M 5) catch fn z.z+z $\rightarrow$ try (M\{x=5\}) catch fn z.z+z}
	\LeftLabel{\textsc{(APP 2)}}
	\UnaryInfC{(fn y.y - 2 (try (M 5) catch fn z.z+z)) $\rightarrow$ (fn y.y - 2 (try (M\{x=5\}) catch fn z.z+z))}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (try (M 5) catch fn z.z+z)) catch fn z.print(z) $\rightarrow$ try (fn y.y - 2 (try (M\{x=5\}) catch fn z.z+z)) catch fn z.print(z)}
\end{prooftree}}}

\textbf{passo 2} \\		
\scalebox{.70}{
\parbox{1cm}{ 
\begin{prooftree} 
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{pari(5) $\rightarrow$ false}
	\LeftLabel{\textsc{(IF)}}
	\UnaryInfC{M\{x=5\} = if pari(5) then 5/2 else throw x $\rightarrow$ if false then 5/2 else throw 5}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (M\{x=5\}) catch fn z.z+z $\rightarrow$ try (M'\{x=5\}) catch fn z.z+z}
	\LeftLabel{\textsc{(APP 2)}}
	\UnaryInfC{(fn y.y - 2 (try (M\{x=5\}) catch fn z.z+z)) $\rightarrow$ (fn y.y - 2 (try (M'\{x=5\}) catch fn z.z+z))}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (try (M\{x=5\}) catch fn z.z+z)) catch fn z.print(z) $\rightarrow$ try (fn y.y - 2 (try (M'\{x=5\}) catch fn z.z+z)) catch fn z.print(z)}
\end{prooftree}}}

\textbf{passo 3}  \\		
\scalebox{.73}{
\parbox{1cm}{
\begin{prooftree}  
	\AxiomC{\textsc{(IF-FALSE)}}
	\UnaryInfC{M'\{x=5\} = if false then 5/2 else throw x $\rightarrow$ throw 5}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (M'\{x=5\}) catch fn z.z+z $\rightarrow$ try (throw 5) catch fn z.z+z}
	\LeftLabel{\textsc{(APP 2)}}
	\UnaryInfC{(fn y.y - 2 (try (M'\{x=5\})) $\rightarrow$ (fn y.y - 2 (try (throw 5) catch fn z.z+z))}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (try (M'\{x=5\}) catch fn z.z+z)) catch fn z.print(z) $\rightarrow$ try (fn y.y - 2 (try (throw 5) catch fn z.z+z)) catch fn z.print(z)}
\end{prooftree}}}

\textbf{passo 4}  \\		
\scalebox{.9}{
\parbox{1cm}{
\begin{prooftree}   
	\AxiomC{\textsc{(TRY HANDLE)}}
	\UnaryInfC{try (throw 5) catch fn z.z+z $\rightarrow$ 5+5}
	\LeftLabel{\textsc{(APP 2)}}
	\UnaryInfC{(fn y.y - 2 (try (throw 5) catch fn z.z+z)) $\rightarrow$ fn y.y - 2 (5+5)}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (try (throw 5) catch fn z.z+z)) catch fn z.print(z) $\rightarrow$ try (fn y.y - 2 (5+5)) catch fn z.print(z)}
\end{prooftree}}}

Al passo 4 si effettua un salto non locale del flusso di controllo a causa dell'eccezione.

\textbf{passo 5} 
\begin{prooftree}   
	\AxiomC{\textsc{(SUM)}}
	\UnaryInfC{5+5 $\rightarrow$ 10}
	\LeftLabel{\textsc{(APP 2)}}
	\UnaryInfC{fn y.y - 2 (5+5) $\rightarrow$ fn y.y - 2 (10)}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (5+5)) catch fn z.print(z) $\rightarrow$ try (fn y.y - 2 (10)) catch fn z.print(z)}
\end{prooftree}

\textbf{passo 6} 
\begin{prooftree}    
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{fn y.y - 2 (10) $\rightarrow$ 10-2}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (fn y.y - 2 (10)) catch fn z.print(z) $\rightarrow$ try (10-2) catch fn z.print(z)}
\end{prooftree}

\textbf{passo 7} 
\begin{prooftree}    
	\AxiomC{\textsc{(MINUS)}}
	\UnaryInfC{10-2 $\rightarrow$ 8}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try (10-2) catch fn z.print(z) $\rightarrow$ try (8) catch fn z.print(z)}
\end{prooftree}

\textbf{passo 8} 
\begin{prooftree}     
	\AxiomC{\textsc{(TRY VAL)}}
	\UnaryInfC{try (8) catch fn z.print(z) $\rightarrow$ 8}
\end{prooftree}

L'eccezione lanciata da throw x in M viene raccolta dal primo catch (quello pi\`u vicino).

\paragraph{e) try ((fn x.x throw 1) (try (M 5) catch fn z.z+z)) catch fn z.print(z)}\mbox{}

\textbf{passo 1}  \\		
\scalebox{.75}{
\parbox{1cm}{
\begin{prooftree}  
	\AxiomC{\textsc{(RAISE APP 2)}}
	\UnaryInfC{fn x.x throw 1 $\rightarrow$ throw 1}
	\LeftLabel{\textsc{(APP 1)}}
	\UnaryInfC{(fn x.x throw 1) (try (M 5) catch fn z.z+z) $\rightarrow$ (throw 1) (try (M 5) catch fn z.z+z)}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try ((fn x.x throw 1) (try (M 5) catch fn z.z+z)) catch fn z.print(z) $\rightarrow$ try ((throw 1) (try (M 5) catch fn z.z+z)) catch fn z.print(z)}
\end{prooftree}}}

\textbf{passo 2} 
\begin{prooftree}   
	\AxiomC{\textsc{(RAISE APP 1)}}
	\UnaryInfC{(throw 1) (try (M 5) catch fn z.z+z) $\rightarrow$ throw 1}
	\LeftLabel{\textsc{(TRY)}}
	\UnaryInfC{try ((throw 1) (try (M 5) catch fn z.z+z)) catch fn z.print(z) $\rightarrow$ try (throw 1) catch fn z.print(z)}
\end{prooftree}

Ai passi 1 e 2 si effettuano dei salti non locali del flusso di controllo a causa dell'eccezione.

\textbf{passo 3} 
\begin{prooftree}    
	\AxiomC{\textsc{(TRY HANDLE)}}
	\UnaryInfC{try (throw 1) catch fn z.print(z) $\rightarrow$ fn z.print(z) 1}
\end{prooftree}

\textbf{passo 4} 
\begin{prooftree}    
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{fn z.print(z) 1 $\rightarrow$ print(1)}
\end{prooftree}

\textbf{passo 5} 
\begin{prooftree}    
	\AxiomC{\textsc{(BETA)}}
	\UnaryInfC{print(1) $\rightarrow$ "stampa 1"}
\end{prooftree}
 
L'eccezione lanciata da throw 1 viene raccolta dall'ultimo catch (in ordine di lettura).

\subsection*{Esercizio 5.2}
Si definisca la semantica operazionale per il linguaggio esteso con i costrutti visti in precedenza: unit, records e varianti.

\subsubsection*{Svolgimento}

\textbf{Unit:} 
Non si aggiungono regole per gestire questo tipo, visto che sono state aggiunti solo un valore e un termine.

\textbf{Record:} 

\begin{prooftree}    
	\AxiomC{\textsc{(RAISE EVAL SELECT)}}
	\UnaryInfC{{throw v}.i $\rightarrow$ throw v}
\end{prooftree} 

La regola SELECT va bene cos\`i e basta per tirare fuori i lanci di eccezione che comunque vengono valutati in seguito tramite altre regole.

\begin{prooftree}    
	\AxiomC{\textsc{(RAISE EVAL RECORD)}}
	\UnaryInfC{{\{ $l_i=x_i$\textsuperscript{i $\in$ 1..j-1}, $l_j$=throw v, $l_k=x_k$\textsuperscript{k $\in$ j+1..n}  \} } $\rightarrow$ throw v}
\end{prooftree} 


\textbf{Varianti:} 

La regola RAISE MATCH non \`e necessaria, in quanto si valuta il valore del variante. Se contiene un lancio di un'eccezione si valuta con RAISE RED MATCH. Se il lancio \`e all'interno del match, allora dev'essere necessariamente all'interno di $M_i$ e viene valutato solo quando si esegue il contenuto di $M_i$.

\begin{prooftree}    
	\AxiomC{\textsc{(RAISE RED MATCH)}}
	\UnaryInfC{throw v match \{ case $l_i=x_i=>M_i$\textsuperscript{i $\in$ 1..n} \} $\rightarrow$ throw v}
\end{prooftree}  


\begin{prooftree}    
	\AxiomC{\textsc{(RAISE VARIANT)}}
	\UnaryInfC{<l=throw v> $\rightarrow$ throw v}
\end{prooftree}

